/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MinVeckaRouteImport } from './routes/min-vecka'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OvningIdRouteImport } from './routes/ovning.$id'
import { Route as KCategoryRouteImport } from './routes/k.$category'

const MinVeckaRoute = MinVeckaRouteImport.update({
  id: '/min-vecka',
  path: '/min-vecka',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OvningIdRoute = OvningIdRouteImport.update({
  id: '/ovning/$id',
  path: '/ovning/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const KCategoryRoute = KCategoryRouteImport.update({
  id: '/k/$category',
  path: '/k/$category',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/min-vecka': typeof MinVeckaRoute
  '/k/$category': typeof KCategoryRoute
  '/ovning/$id': typeof OvningIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/min-vecka': typeof MinVeckaRoute
  '/k/$category': typeof KCategoryRoute
  '/ovning/$id': typeof OvningIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/min-vecka': typeof MinVeckaRoute
  '/k/$category': typeof KCategoryRoute
  '/ovning/$id': typeof OvningIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/min-vecka' | '/k/$category' | '/ovning/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/min-vecka' | '/k/$category' | '/ovning/$id'
  id: '__root__' | '/' | '/auth' | '/min-vecka' | '/k/$category' | '/ovning/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  MinVeckaRoute: typeof MinVeckaRoute
  KCategoryRoute: typeof KCategoryRoute
  OvningIdRoute: typeof OvningIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/min-vecka': {
      id: '/min-vecka'
      path: '/min-vecka'
      fullPath: '/min-vecka'
      preLoaderRoute: typeof MinVeckaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ovning/$id': {
      id: '/ovning/$id'
      path: '/ovning/$id'
      fullPath: '/ovning/$id'
      preLoaderRoute: typeof OvningIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/k/$category': {
      id: '/k/$category'
      path: '/k/$category'
      fullPath: '/k/$category'
      preLoaderRoute: typeof KCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  MinVeckaRoute: MinVeckaRoute,
  KCategoryRoute: KCategoryRoute,
  OvningIdRoute: OvningIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
